firstsite/RentBis/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('ad/', include('ads.urls')),
    path('polls/', include('polls.urls'))
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

firstsite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),

    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

firstsite/cats/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.CatMainView.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('CatLookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('CatLookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('CatLookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
]

firstsite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
        max_length=200,
        validators = [MinLengthValidator(2, "Breed must be at least 2 characters.")]
        )
    def __str__(self):
        return self.name
    
    
class Cat(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators = [MinLengthValidator(2, "Nickname must be at least 2 characters.")]
        )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)
    
    def __str__(self):
        return self.nickname

    

firstsite/cats/forms.py
from django.forms import ModelForm
from cats.models import Breed


class BreedForm(ModelForm):
    class Meta:
        model = Breed
        fields = '__all__'

firstsite/cats/views.py
from django.shortcuts import get_object_or_404, render, redirect, get_list_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from cats.models import Breed, Cat
from cats.forms import BreedForm


class CatMainView(LoginRequiredMixin, View):
    def get(self, request):
        mc = Breed.objects.all().count()
        al = Cat.objects.all()
    
        ctx = {'breed_count': mc, 'cat_list': al} 
        return render(request, 'cats/cat_list.html', ctx)
    
    
class BreedView(LoginRequiredMixin, View):
    def get(self, request):
        ml = Breed.objects.all()
        ctx = {'breed_list': ml}
        return render(request, 'cats/breed_list.html', ctx)
    
    
class BreedCreate(LoginRequiredMixin, View):
    template = 'cats/breed_form.html'
    success_url = reverse_lazy('cats:all')

    def get(self, request):
        form = BreedForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)
    
    def post(self, request):
        form = BreedForm(request.POST) 
        if not form.is_valid():
            ctx = {'form': form}
            return render (request, self.template, ctx)
        
        make = form.save()
        return redirect(self.success_url)
    
    
class BreedUpdate(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('cats:all')
    template = 'cats/breed_form.html'
    
    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = BreedForm(instance=make)
        ctx = {'form': form}
        return render(request, self.template, ctx)
    
    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = BreedForm(request.POST, instance=make)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)
        
        form.save()
        return redirect(self.success_url)
    
    
class BreedDelete(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('cats:all')
    template = 'cats/breed_confirm_delete.html'

    def get(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        form = BreedForm(instance=make)
        ctx = {'Breed': make}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        make = get_object_or_404(self.model, pk=pk)
        make.delete()
        return redirect(self.success_url)
    
    
class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

firstsite/cats/templates/cats/breed_confirm_delete.html
<head> 
  <meta name="dj4e" content="b9c72b87254f0b30ae977c99e10b729e"> 
</head>

{% extends "base_menu.html" %}

{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

firstsite/cats/templates/cats/breed_form.html
<head> 
  <meta name="dj4e" content="b9c72b87254f0b30ae977c99e10b729e"> 
</head>

{% extends "base_menu.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

firstsite/cats/templates/cats/breed_list.html
<head> 
  <meta name="dj4e" content="b9c72b87254f0b30ae977c99e10b729e"> 
</head>

{% extends "base_menu.html" %}

{% block content %}
  <h1>Breed List</h1>
  {% if breed_list %}
  <ul>
    {% for breed in breed_list %}
      <li>
          {{ breed.name }}
         (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
          <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no breeds in the library.</p>
  {% endif %}
  <p><a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
  <p>
    <a href="{% url 'cats:all' %}">Back to cats kitties kity cats</a>
  </p>
{% endblock %}

firstsite/cats/templates/cats/cat_confirm_delete.html
<head> 
  <meta name="dj4e" content="b9c72b87254f0b30ae977c99e10b729e"> 
</head>
{% extends "base_menu.html" %}

{% block content %}

<h1>Delete Auto</h1>


<p>Are you sure you want to delete the cat <:( : {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete >:\ .">
</form>

{% endblock %}

firstsite/cats/templates/cats/cat_form.html
<head> 
  <meta name="dj4e" content="b9c72b87254f0b30ae977c99e10b729e"> 
</head>

{% extends "base_menu.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

firstsite/cats/templates/cats/cat_list.html
<head> 
  <meta name="dj4e" content="b9c72b87254f0b30ae977c99e10b729e"> 
</head>

{% extends "base_menu.html" %}

{% block content %}
  <h1>Cat List</h1>

  {% if cat_list %}
  <ul>
    {% for cat in cat_list %}
      <li>
          {{ cat.nickname }} ({{ cat.breed }})
          (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
          <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>) <br/>
          {{ cat.weight }} ({{ cat.foods }} )
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cats in the library.</p>
  {% endif %}
  <p>
    {% if breed_count > 0 %}
      <a href="{% url 'cats:cat_create' %}">Add a cat</a>
    {% else %}
      Please add a breed before you add a cat.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) | 
    <a href="{% url 'cats:breed_create' %}">Add a breed</a>
  </p>
{% endblock %}